"""initial schema

Revision ID: 5dd7bb91b678
Revises: 
Create Date: 2026-07-16 01:34:00.888160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dd7bb91b678'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('email_normalized', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_normalized')
    )
    op.create_table('audit_logs',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_organization_id', 'audit_logs', ['organization_id'], unique=False)
    op.create_table('chip_ledger_entries',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('reference_type', sa.String(length=100), nullable=True),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chip_ledger_entries_organization_id', 'chip_ledger_entries', ['organization_id'], unique=False)
    op.create_table('entitlements',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('feature_key', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'feature_key', name='uq_entitlements_org_feature')
    )
    op.create_index('ix_entitlements_organization_id', 'entitlements', ['organization_id'], unique=False)
    op.create_table('memberships',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_memberships_org_user')
    )
    op.create_index('ix_memberships_organization_id', 'memberships', ['organization_id'], unique=False)
    op.create_table('persona_presets',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_persona_presets_org_name')
    )
    op.create_index('ix_persona_presets_organization_id', 'persona_presets', ['organization_id'], unique=False)
    op.create_table('projects',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_projects_org_name')
    )
    op.create_index('ix_projects_organization_id', 'projects', ['organization_id'], unique=False)
    op.create_table('test_definitions',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_test_definitions_project_name')
    )
    op.create_index('ix_test_definitions_organization_id', 'test_definitions', ['organization_id'], unique=False)
    op.create_index('ix_test_definitions_project_id', 'test_definitions', ['project_id'], unique=False)
    op.create_table('test_variants',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('test_definition_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_definition_id'], ['test_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_definition_id', 'name', name='uq_test_variants_definition_name')
    )
    op.create_index('ix_test_variants_organization_id', 'test_variants', ['organization_id'], unique=False)
    op.create_index('ix_test_variants_test_definition_id', 'test_variants', ['test_definition_id'], unique=False)
    op.create_table('simulation_runs',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('test_variant_id', sa.Uuid(), nullable=False),
    sa.Column('persona_preset_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='simulation_status'), nullable=False),
    sa.Column('deterministic_seed', sa.BigInteger(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('calibration_status', sa.Enum('UNCALIBRATED', 'CALIBRATING', 'CALIBRATED', name='calibration_status'), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['persona_preset_id'], ['persona_presets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_variant_id'], ['test_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_simulation_runs_organization_id', 'simulation_runs', ['organization_id'], unique=False)
    op.create_index('ix_simulation_runs_test_variant_id', 'simulation_runs', ['test_variant_id'], unique=False)
    op.create_table('reports',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('simulation_run_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reports_organization_id', 'reports', ['organization_id'], unique=False)
    op.create_index('ix_reports_simulation_run_id', 'reports', ['simulation_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reports_simulation_run_id', table_name='reports')
    op.drop_index('ix_reports_organization_id', table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_simulation_runs_test_variant_id', table_name='simulation_runs')
    op.drop_index('ix_simulation_runs_organization_id', table_name='simulation_runs')
    op.drop_table('simulation_runs')
    op.drop_index('ix_test_variants_test_definition_id', table_name='test_variants')
    op.drop_index('ix_test_variants_organization_id', table_name='test_variants')
    op.drop_table('test_variants')
    op.drop_index('ix_test_definitions_project_id', table_name='test_definitions')
    op.drop_index('ix_test_definitions_organization_id', table_name='test_definitions')
    op.drop_table('test_definitions')
    op.drop_index('ix_projects_organization_id', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_persona_presets_organization_id', table_name='persona_presets')
    op.drop_table('persona_presets')
    op.drop_index('ix_memberships_organization_id', table_name='memberships')
    op.drop_table('memberships')
    op.drop_index('ix_entitlements_organization_id', table_name='entitlements')
    op.drop_table('entitlements')
    op.drop_index('ix_chip_ledger_entries_organization_id', table_name='chip_ledger_entries')
    op.drop_table('chip_ledger_entries')
    op.drop_index('ix_audit_logs_organization_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
    # Postgres ENUM turleri tablo drop edildiginde otomatik silinmez;
    # downgrade'in tekrar calistirilabilir olmasi icin acikca temizliyoruz.
    sa.Enum(name='calibration_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='simulation_status').drop(op.get_bind(), checkfirst=True)
