"""chip entitlement lifecycle and reservations

Revision ID: 8fb5df830eac
Revises: 5dd7bb91b678
Create Date: 2026-07-16 07:45:33.642397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fb5df830eac'
down_revision: Union[str, Sequence[str], None] = '5dd7bb91b678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    # `op.add_column` (create_table'in aksine) ENUM turunu otomatik olusturmaz;
    # asagida add_column ile kullanilacak turleri once acikca olustururuz.
    entry_type_enum = sa.Enum(
        'CREDIT', 'RESERVE', 'CONSUME', 'RELEASE', 'ADJUSTMENT', name='chip_ledger_entry_type'
    )
    entry_type_enum.create(bind, checkfirst=True)
    entitlement_status_enum = sa.Enum('AVAILABLE', 'RESERVED', 'CONSUMED', name='entitlement_status')
    entitlement_status_enum.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chip_reservations',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('RESERVED', 'CONSUMED', 'RELEASED', name='chip_reservation_status'), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'idempotency_key', name='uq_chip_reservations_org_idem')
    )
    op.create_index('ix_chip_reservations_organization_id', 'chip_reservations', ['organization_id'], unique=False)
    # `entry_type` mevcut satirlar icin bir varsayilan gerektirir (once dolu
    # olarak eklenir, sonra varsayilan kaldirilir ki yeni satirlar ORM
    # tarafindan acikca belirtilmek zorunda kalsin).
    op.add_column(
        'chip_ledger_entries',
        sa.Column(
            'entry_type',
            entry_type_enum,
            nullable=False,
            server_default='CREDIT',
        ),
    )
    op.alter_column('chip_ledger_entries', 'entry_type', server_default=None)
    op.add_column('chip_ledger_entries', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.create_unique_constraint('uq_chip_ledger_entries_org_idem', 'chip_ledger_entries', ['organization_id', 'idempotency_key'])
    op.add_column(
        'entitlements',
        sa.Column(
            'status',
            entitlement_status_enum,
            nullable=False,
            server_default='AVAILABLE',
        ),
    )
    op.alter_column('entitlements', 'status', server_default=None)
    op.add_column('entitlements', sa.Column('reserved_run_id', sa.Uuid(), nullable=True))
    op.add_column('entitlements', sa.Column('reserved_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entitlements', 'reserved_until')
    op.drop_column('entitlements', 'reserved_run_id')
    op.drop_column('entitlements', 'status')
    op.drop_constraint('uq_chip_ledger_entries_org_idem', 'chip_ledger_entries', type_='unique')
    op.drop_column('chip_ledger_entries', 'idempotency_key')
    op.drop_column('chip_ledger_entries', 'entry_type')
    op.drop_index('ix_chip_reservations_organization_id', table_name='chip_reservations')
    op.drop_table('chip_reservations')
    # ### end Alembic commands ###
    # Postgres ENUM turleri tablo/kolon drop edildiginde otomatik silinmez;
    # downgrade'in tekrar calistirilabilir olmasi icin acikca temizliyoruz.
    sa.Enum(name='entitlement_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='chip_ledger_entry_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='chip_reservation_status').drop(op.get_bind(), checkfirst=True)
