/**
 * Eski backend kayıtlarında Türkçe karakter kullanılmadan saklanmış sistem
 * metinlerini düzeltir. Kullanıcının yazdığı serbest metinlere uygulanmaz.
 */
export function normalizeTurkishSystemCopy(value: string): string {
  const replacements: Array<[RegExp, string]> = [
    [
      /\bAB\/grup karsilastirmasi (?:tuketildi|serbest birakildi)\b/g,
      "A/B grup karşılaştırması",
    ],
    [/\bAI pipeline\b/g, "AI işlem hattı"],
    [/\bLaunch grubu\b/g, "Başlatma grubu"],
    [/\bAB\/grup karsilastirmasi\b/g, "A/B grup karşılaştırması"],
    [/\bpersona kohortlarıyla\b/g, "persona gruplarıyla"],
    [/\bon kontrolu\b/g, "ön kontrolü"],
    [/\bon taramasi\b/g, "ön taraması"],
    [/\bgoz izleme\b/g, "göz izleme"],
    [/\bGecersiz\b/g, "Geçersiz"],
    [/\bgecersiz\b/g, "geçersiz"],
    [/\bgecerli\b/g, "geçerli"],
    [/\bbulunamadi\b/g, "bulunamadı"],
    [/\bsuresi\b/g, "süresi"],
    [/\bdolmus\b/g, "dolmuş"],
    [/\bislem\b/g, "işlem"],
    [/\bicin\b/g, "için"],
    [/\bdogrulamasi\b/g, "doğrulaması"],
    [/\bdogrulama\b/g, "doğrulama"],
    [/\bbasarisiz\b/g, "başarısız"],
    [/\bbasarili\b/g, "başarılı"],
    [/\bUretim\b/g, "Üretim"],
    [/\buretilen\b/g, "üretilen"],
    [/\bArsivlenmis\b/g, "Arşivlenmiş"],
    [/\bguncellenemez\b/g, "güncellenemez"],
    [/\bTasarim\b/g, "Tasarım"],
    [/\btasarimin\b/g, "tasarımın"],
    [/\btasarim\b/g, "tasarım"],
    [/\bayni\b/g, "aynı"],
    [/\bgorseli\b/g, "görseli"],
    [/\bgorsel\b/g, "görsel"],
    [/\bartik\b/g, "artık"],
    [/\bkullanilabilirlik\b/g, "kullanılabilirlik"],
    [/\bkullanilabilir\b/g, "kullanılabilir"],
    [/\bdegil\b/g, "değil"],
    [/\bdegildir\b/g, "değildir"],
    [/\bgoruntusu\b/g, "görüntüsü"],
    [/\bCalistirma\b/g, "Çalıştırma"],
    [/\bUcretsiz\b/g, "Ücretsiz"],
    [/\bKarsilastirma\b/g, "Karşılaştırma"],
    [/\bkarsilastirilmasi\b/g, "karşılaştırılması"],
    [/\bkarsilastirmasi\b/g, "karşılaştırması"],
    [/\byalnizca\b/g, "yalnızca"],
    [/\bvaryantin\b/g, "varyantın"],
    [/\bbasariyla\b/g, "başarıyla"],
    [/\btamamlanmis\b/g, "tamamlanmış"],
    [/\bBaslatilmis\b/g, "Başlatılmış"],
    [/\bdegistirilemez\b/g, "değiştirilemez"],
    [/\barasinda\b/g, "arasında"],
    [/\bolmalidir\b/g, "olmalıdır"],
    [/\bBos\b/g, "Boş"],
    [/\byuklenemez\b/g, "yüklenemez"],
    [/\byukleme\b/g, "yükleme"],
    [/\bkayitli\b/g, "kayıtlı"],
    [/\bguvenlik\b/g, "güvenlik"],
    [/\bsonlandirildi\b/g, "sonlandırıldı"],
    [/\blutfen\b/g, "lütfen"],
    [/\bgiris\b/g, "giriş"],
    [/\bolusturulamadi\b/g, "oluşturulamadı"],
    [/\btum\b/g, "tüm"],
    [/\btuketildi\b/g, "tüketildi"],
    [/\bserbest birakildi\b/g, "serbest bırakıldı"],
    [/\bgorev\b/g, "görev"],
    [/\bGorev\b/g, "Görev"],
    [/\bSimulasyon\b/g, "Simülasyon"],
    [/\bsimulasyon\b/g, "simülasyon"],
    [/\bsonuclarindan\b/g, "sonuçlarından"],
    [/\bcok\b/g, "çok"],
    [/\basamali\b/g, "aşamalı"],
    [/\biceren\b/g, "içeren"],
    [/\bgelismis\b/g, "gelişmiş"],
    [/\bdavranisi\b/g, "davranışı"],
    [/\bucretlendirilir\b/g, "ücretlendirilir"],
    [/\bucreti\b/g, "ücreti"],
    [/\bakisini\b/g, "akışını"],
    [/\bkohortlariyla\b/g, "kohortlarıyla"],
    [/\bdegerlendiren\b/g, "değerlendiren"],
    [/\bdegerlendirmesi\b/g, "değerlendirmesi"],
    [/\bolasiligi\b/g, "olasılığı"],
    [/\bYanlis\b/g, "Yanlış"],
    [/\btiklama\b/g, "tıklama"],
    [/\bErisilebilirlik\b/g, "Erişilebilirlik"],
    [/\berisilebilirlik\b/g, "erişilebilirlik"],
    [/\bkontrasti\b/g, "kontrastı"],
    [/\bkurallarina\b/g, "kurallarına"],
    [/\bdayali\b/g, "dayalı"],
    [/\btaramasi\b/g, "taraması"],
    [/\bbulgulari\b/g, "bulguları"],
    [/\bFarkli\b/g, "Farklı"],
    [/\bfarkli\b/g, "farklı"],
    [/\bAg\b/g, "Ağ"],
    [/\bag\b/g, "ağ"],
    [/\bhizi\b/g, "hızı"],
    [/\bolcumu\b/g, "ölçümü"],
    [/\bbasina\b/g, "başına"],
    [/\borani\b/g, "oranı"],
    [/\bsayfalarindaki\b/g, "sayfalarındaki"],
    [/\bgecirici\b/g, "geçirici"],
    [/\bogelerin\b/g, "öğelerin"],
    [/\betkilesim\b/g, "etkileşim"],
    [/\bbazli\b/g, "bazlı"],
    [/\bmesaji\b/g, "mesajı"],
    [/\bnetligi\b/g, "netliği"],
    [/\bduzeninden\b/g, "düzeninden"],
    [/\bturetilen\b/g, "türetilen"],
    [/\bedilmemis\b/g, "edilmemiş"],
    [/\bagirlik\b/g, "ağırlık"],
    [/\baginlik\b/g, "ağırlık"],
    [/\bgercek\b/g, "gerçek"],
    [/\byogunluk\b/g, "yoğunluk"],
    [/\bharitasi\b/g, "haritası"],
    [/\bozeti\b/g, "özeti"],
    [/\bozet\b/g, "özet"],
    [/\bozetleri\b/g, "özetleri"],
    [/\bsureleri\b/g, "süreleri"],
    [/\bdavranis\b/g, "davranış"],
    [/\bilgi puani\b/g, "ilgi puanı"],
    [/\baciklama\b/g, "açıklama"],
    [/\bhesaplanmis\b/g, "hesaplanmış"],
    [/\bkarari\b/g, "kararı"],
    [/\bKisa\b/g, "Kısa"],
    [/\bOlasi\b/g, "Olası"],
    [/\baciklamalar\b/g, "açıklamalar"],
    [/\bOnerilen\b/g, "Önerilen"],
  ];

  return replacements.reduce(
    (text, [pattern, replacement]) => text.replace(pattern, replacement),
    value,
  );
}
